module GitHub
  module Replicator
    # Dump replicants in a streaming fashion.
    #
    # The Dumper takes an ActiveRecord object and generates one or more replicant
    # objects. A replicant object has the form: [type, id, attributes] and
    # describes exactly one record in the database. The type and id identify the
    # record's model class name string and primary key id, respectively. The
    # attributes is a Hash of primitive typed objects generated by a call to
    # ActiveRecord::Base#attributes.
    #
    # Dumping to an array:
    #
    #     >> replicator = Replicator::Dumper.new
    #     >> replicator.dump_repository User / :defunkt / :github
    #     >> pp replicator.to_a
    #
    # Dumping to stdout in marshal format:
    #
    #     >> writer = lambda { |*a| Marshal.dump(a, $stdout) }
    #     >> replicator = Replicator::Dumper.new(&writer)
    #     >> replicator.dump_repository User / :defunkt / :github
    #
    class Dumper
      def initialize(io=nil, &write)
        write ||= lambda { |*replicant| Marshal.dump(replicant, io) } if io
        write ||= lambda { |*replicant| @objects << replicant }
        @objects = []
        @write = write
        @memo = {}
      end

      # Grab dumped objects array. Always empty when a custom write function was
      # provided when initialized.
      def to_a
        @objects
      end

      # Check if object has been dumped yet.
      def dumped?(object)
        @memo["#{object.class}:#{object.id}"]
      end

      # Call the write method given in the initializer or write to the internal
      # objects array when no write method was given.
      #
      # type       - The model class name as a String.
      # id         - The record's id. Usually an integer.
      # attributes - All model attributes.
      #
      # Returns nothing.
      def write(type, id, attributes)
        @write.call(type, id, attributes)
      end

      # Dump one or more objects to the internal array or provided dump
      # stream. This method guarantees that the same object will not be dumped
      # more than once.
      #
      # objects - ActiveRecord object instances.
      #
      # Returns nothing.
      def dump(*objects)
        objects = objects[0] if objects.size == 1 && objects[0].is_a?(Array)
        objects.each do |object|
          next if object.nil?
          next if dumped?(object)

          meth = "dump_#{object.class.to_s.underscore}"
          if respond_to?(meth)
            send meth, object
          else
            dump_object object
          end
        end
      end

      # Low level dump method. Generates a call to write with the attributes of
      # the given objects. This method is used in dumpspecs when dumping the
      # dumpspec's subject.
      def dump_object(object)
        return if dumped?(object)
        @memo["#{object.class}:#{object.id}"] = object
        write object.class.name, object.id, object.attributes
      end

      ##
      # Dumpspecs

      def dump_repository(repository)
        dump repository.owner
        dump repository.plan_owner
        dump_object repository
        dump repository.issues
      end

      def dump_user(user)
        dump_object user
        dump user.profile
        dump user.emails
      end

      def dump_issue(issue)
        dump issue.repository
        dump issue.user
        dump issue.assignee
        dump issue.milestone
        dump issue.pull_request
        dump_object issue
        dump issue.comments
      end

      def dump_issue_comment(comment)
        dump comment.user
        dump comment.repository
        dump_object comment
      end

      def dump_pull_request(pull)
        dump pull.repository
        dump pull.head_repository
        dump pull.base_repository
        dump pull.user
        dump pull.base_user
        dump pull.head_user
        dump_object pull
        dump pull.review_comments
      end

      def dump_pull_request_review_comment(comment)
        dump comment.user
        dump comment.pull_request
        dump_object comment
      end
    end

    # Load replicants in a streaming fashion.
    #
    # The Loader reads [type, id, attributes] replicant tuples and creates
    # objects in the current environment.
    #
    # Objects are expected to arrive in order such that a record referenced via
    # foreign key always precedes the referencing record. The Loader maintains a
    # mapping of primary keys from the dump system to the current environment.
    # This mapping is used to properly establish new foreign key values on all
    # records inserted.
    class Loader
      def initialize
        fail "not ready for production" if RAILS_ENV == 'production'
        @keymap = {}
      end

      # Read replicant tuples from the given IO object and load into the
      # database within a single transaction.
      def read(io)
        ActiveRecord::Base.transaction do
          while object = Marshal.load(io)
            type, id, attrs = object
            record = load(type, id, attrs)
            yield record if block_given?
          end
        end
      rescue EOFError
      end

      # Load an individual record into the database.
      #
      # type  - Model class name as a String.
      # id    - Primary key id of the record on the dump system. This must be
      #         translated to the local system and stored in the keymap.
      # attrs - Hash of attributes to set on the new record.
      #
      # Returns the ActiveRecord object instance for the new record.
      def load(type, id, attributes)
        model = Object::const_get(type)
        instance = load_object model, attributes
        primary_key = nil

        # write each attribute separately, converting foreign key values to
        # their local system values.
        attributes.each do |key, value|
          if key == model.primary_key
            primary_key = value
            next
          elsif key =~ /^(.*)_id$/
            if value && reflection = model.reflect_on_association($1.to_sym)
              dependent_model = Object::const_get(reflection.class_name)
              if record = find_dependent_object(dependent_model, value)
                instance.write_attribute key, record.id
              else
                warn "error: #{model} referencing #{dependent_model}[#{value}] " \
                     "not found in keymap"
              end
            elsif value
              warn "warn: association not found for #{model}.#{key} attribute. nilifying."
              instance.write_attribute key, value
            end
          else
            instance.write_attribute key, value
          end
        end

        # write to the database without validations and callbacks, register in
        # the keymap and return the AR object
        instance.save false
        register_dependent_object instance, primary_key
        instance
      end

      # Find the local AR object instance for the given model class and dump
      # system primary key.
      #
      # model - An ActiveRecord subclass.
      # id    - The dump system primary key id.
      #
      # Returns the AR object instance if found, nil otherwise.
      def find_dependent_object(model, id)
        @keymap["#{model}:#{id}"]
      end

      # Register a newly created or updated AR object in the keymap.
      #
      # object - An ActiveRecord object instance.
      # id     - The dump system primary key id.
      #
      # Returns object.
      def register_dependent_object(object, id)
        model = object.class
        while model != ActiveRecord::Base && model != Object
          @keymap["#{model}:#{id}"] = object
          model = model.superclass
        end
        object
      end

      # Load an AR instance from the current environment.
      #
      # model - The ActiveRecord class to search for.
      # attrs - Hash of dumped record attributes.
      #
      # Returns an instance of model. This is usually a new record instance but
      # can be overridden to return an existing record instead.
      def load_object(model, attributes)
        meth = "load_#{model.to_s.underscore}"
        instance =
          if respond_to?(meth)
            send(meth, attributes) || model.new
          else
            model.new
          end
        def instance.callback(*args);end # Rails 2.x hack to disable callbacks.
        instance
      end

      ##
      # Loadspecs

      # Use existing users when the login is available.
      def load_user(attrs)
        User.find_by_login(attrs['login'])
      end

      # Delete existing repositories and create new ones. Nice because we don't
      # have to worry about updating existing issues, comments, etc.
      def load_repository(attrs)
        owner = find_dependent_object(User, attrs['owner_id'])
        if repo = Repository.find_by_name_with_owner("#{owner.login}/#{attrs['name']}")
          warn "warn: deleting existing repository: #{repo.name_with_owner} (#{repo.id})"
          repo.destroy
        end
        Repository.new
      end
    end
  end
end
