#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Ar3X::Application.load_tasks

task :db do
  url = "http://downloads.mysql.com/docs/world.sql.gz"
end
